version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: brag_document
      POSTGRES_USER: brag_user
      POSTGRES_PASSWORD: brag_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: