# Generated by Django 5.2.7 on 2025-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BragDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=50)),
                ('excel_file', models.FileField(upload_to='excel_files/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('work_accomplishments', models.JSONField()),
                ('learning', models.JSONField()),
                ('utilized_skills', models.JSONField()),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
