# Generated by Django 5.2.7 on 2025-10-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brag_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bragdocument',
            name='excel_file',
        ),
    ]
