# Generated by Django 5.2.7 on 2025-10-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brag_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bragdocument",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bragdocument",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bragdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="learning",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="utilized_skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="work_accomplishments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
