# Generated by Django 5.2.7 on 2025-10-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "brag_generator",
            "0002_bragdocument_completed_at_bragdocument_error_message_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bragdocument",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="bragdocument",
            name="error_message",
        ),
        migrations.RemoveField(
            model_name="bragdocument",
            name="status",
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="learning",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="utilized_skills",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="bragdocument",
            name="work_accomplishments",
            field=models.JSONField(default=dict),
        ),
    ]
